<?php

/* 
 * This will be a custom set of migration classes for a migration demo.
 */

/*
 * Implementation of hook_migrate_api.
 */
function epomigrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/*
 * Implementation of hook_init
 */
function epomig_init() {
  Database::addConnectionInfo('for_migration', 'default', array(
    'driver' => 'mysql',
    'database' => 'migrations',
    'username' => 'root',
    'password' => '',
    'host' => 'localhost',
    'prefix' => '',
  ));
}
